language: node_js
node_js:
  - "18"
install:
  - npm install
  - cd client && npm install
script:
  - cd client && npm run build
  - cd ..
deploy:
  provider: heroku
  app: gymate-app-prod
  on:
    branch: main